# Generated by Django 4.0 on 2021-12-25 17:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0003_rename_description_doctor_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], max_length=10)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('CF', 'Confirmed'), ('CC', 'Cancelled')], default='Pending', max_length=2)),
                ('note', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
