# Generated by Django 4.0 on 2021-12-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0003_rename_description_doctor_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('blood', models.CharField(max_length=4)),
                ('bag', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(max_length=250)),
                ('marital_status', models.CharField(choices=[('SI', 'Single'), ('MA', 'Married'), ('WI', 'Windowed'), ('SE', 'Separated'), ('NT', 'Not Specified')], max_length=2, verbose_name='Marital Status')),
                ('photo_url', models.ImageField(blank=True, help_text='Allowed size is 200MB', null=True, upload_to='patients/%Y-%m-%d/', verbose_name='Photo URL')),
                ('description', models.TextField(blank=True, null=True)),
                ('blood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patient.bloodbank')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospital.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
