# Generated by Django 4.0 on 2021-12-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, help_text='Allowed size is 10MB', null=True, upload_to='categories/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('balance', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, help_text='Allowed size is 10MB', null=True, upload_to='medicinetypes/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('icon', models.ImageField(blank=True, help_text='Allowed size is 20MB', null=True, upload_to='units/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('barcode_or_qrcode', models.CharField(max_length=50, verbose_name='Barcode or QR Code')),
                ('medicine_name', models.CharField(max_length=100, verbose_name='Medicine Name')),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('generic_name', models.CharField(max_length=50, verbose_name='Generic Name')),
                ('box_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Box Size')),
                ('medicine_shelf', models.CharField(blank=True, max_length=50, null=True, verbose_name='Medicine Shelf')),
                ('manufacturer_price', models.FloatField(default=0.0, verbose_name='Manufacturer Price')),
                ('sell_price', models.FloatField(default=0.0, verbose_name='Sell Price')),
                ('tax', models.FloatField(default=0.0)),
                ('vat', models.FloatField(default=0.0)),
                ('photo_url', models.ImageField(blank=True, help_text='Allowed size is 200MB', null=True, upload_to='medicines/%Y-%m-%d/', verbose_name='Photo URL')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicine.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicine.manufacturer')),
                ('medicine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicine.medicinetype', verbose_name='Medicine Type')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicine.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
