# Generated by Django 4.0 on 2021-12-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Vehicle Number')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=1988)),
                ('driver_name', models.CharField(max_length=50, verbose_name='Driver Name')),
                ('driver_contact', models.CharField(max_length=20, verbose_name='Driver Contact')),
                ('vehicle_type', models.CharField(choices=[('O', 'Owned'), ('C', 'Contractual')], default='Owned', max_length=2, verbose_name='Vehicle Type')),
                ('driver_license', models.BooleanField(default=True, verbose_name='Driver License')),
                ('photo_url', models.ImageField(blank=True, help_text='Allowed size is 200MB', null=True, upload_to='ambulances/', verbose_name='Photo URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, help_text='Allowed size is 10MB', null=True, upload_to='departments/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=2)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('nationality', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(max_length=250)),
                ('photo_url', models.ImageField(help_text='Allowed size is 200MB', upload_to='doctors/%Y-%m-%d/', verbose_name='Photo URL')),
                ('twitter', models.CharField(blank=True, max_length=120, null=True)),
                ('facebook', models.CharField(blank=True, max_length=120, null=True)),
                ('instagram', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('department', models.ManyToManyField(related_name='doctors', to='hospital.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('location', models.CharField(max_length=250)),
                ('logo_url', models.ImageField(blank=True, help_text='Allowed size is 100MB', null=True, upload_to='experiences/%Y-%m-%d/', verbose_name='Logo URL')),
                ('position', models.CharField(max_length=100)),
                ('start_work', models.DateField(verbose_name='Start Work')),
                ('end_work', models.DateField(verbose_name='End Work')),
                ('responsibilities', models.CharField(max_length=250)),
                ('skill_used', models.CharField(max_length=250, verbose_name='Skill Used')),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='hospital.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(max_length=150, verbose_name='School Name')),
                ('major', models.CharField(max_length=150)),
                ('start_year', models.DateField(verbose_name='Start Year')),
                ('end_year', models.DateField(verbose_name='End Year')),
                ('logo_url', models.ImageField(blank=True, help_text='Allowed size is 100MB', null=True, upload_to='educations/%Y-%m-%d/', verbose_name='Logo URL')),
                ('activities_societies', models.CharField(max_length=250, verbose_name='Activity Societies')),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='hospital.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='language',
            field=models.ManyToManyField(related_name='doctors', to='hospital.Language'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.ManyToManyField(related_name='doctors', to='hospital.Speciality'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('thumbnail', models.ImageField(upload_to='articles/')),
                ('cover_url', models.ImageField(help_text='Allowed size is 200MB', upload_to='articles/%Y-%m-%d/', verbose_name='Cover URL')),
                ('image1', models.ImageField(blank=True, help_text='Allowed size is 500MB', null=True, upload_to='articles/%Y-%m-%d/', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, help_text='Allowed size is 500MB', null=True, upload_to='articles/%Y-%m-%d/', verbose_name='Image 2')),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='hospital.doctor')),
                ('tag', models.ManyToManyField(related_name='articles', to='hospital.Speciality')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
