# Generated by Django 4.0 on 2021-12-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_language_code_language_country_language_dial_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='description',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
    ]
